// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKxkFflB2x3nGDKsAfSVUNEh2dVrXhzs',
    appId: '1:567828966693:web:b827ae46b4588db0b7fecc',
    messagingSenderId: '567828966693',
    projectId: 'gestura-vn-sign-language-app',
    authDomain: 'gestura-vn-sign-language-app.firebaseapp.com',
    databaseURL: 'https://gestura-vn-sign-language-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestura-vn-sign-language-app.firebasestorage.app',
    measurementId: 'G-5R3Y6EZ438',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDURwWH4154ttQVpmlflY0Ten7pCMUYSO0',
    appId: '1:567828966693:android:4fea2183b7e639f1b7fecc',
    messagingSenderId: '567828966693',
    projectId: 'gestura-vn-sign-language-app',
    databaseURL: 'https://gestura-vn-sign-language-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestura-vn-sign-language-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzYAzKQbPQYyOZcHavEKWD-jH3gjNfWE0',
    appId: '1:567828966693:ios:3ff6f2f817e3be84b7fecc',
    messagingSenderId: '567828966693',
    projectId: 'gestura-vn-sign-language-app',
    databaseURL: 'https://gestura-vn-sign-language-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestura-vn-sign-language-app.firebasestorage.app',
    iosClientId: '567828966693-a88n5a9g9u6lkrh33i7n43dqp8f4cim4.apps.googleusercontent.com',
    iosBundleId: 'com.example.howToUseProvider',
  );
}
